Imports DevExpress.XtraPivotGrid
Imports System.Windows.Forms

Namespace WinPivot_CustomFunctions
	Partial Public Class Form1
		Inherits Form
		Public Sub New()
			InitializeComponent()
			' This line of code is generated by Data Source Configuration Wizard
			salesPersonTableAdapter1.Fill(nwindDataSet1.SalesPerson)
			pivotGridControl1.BestFit()
			pivotGridControl1.OptionsView.ShowColumnTotals = False
			pivotGridControl1.OptionsView.ShowRowTotals = False
			pivotGridControl1.OptionsView.ShowRowGrandTotals = False
			pivotGridControl1.OptionsData.DataProcessingEngine = PivotDataProcessingEngine.Optimized
			Dim pivotGridField1 As New PivotGridField() With {
				.Area = PivotArea.DataArea,
				.AreaIndex = 0,
				.Caption = "First Product Sold",
				.FieldName = "FirstProductSold"
			}
			pivotGridControl1.Fields.Add(pivotGridField1)
			pivotGridField1.DataBinding = New ExpressionDataBinding() With {.Expression = "FirstValue([ProductName])"}
			pivotGridField1.Options.ShowUnboundExpressionMenu = True
			pivotGridField1.Options.ShowGrandTotal = False
		End Sub
	End Class
End Namespace
